version: '3'

services:
  analysis_env:
    image: illumination27/marpolseq:v0.1

    container_name: marpolseq

    user: root

    privileged: true
    
    volumes:
      - "./workspace:/workspace"

    command: sh -c "sleep infinity"